AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AwsNamespace:
    Type: String
    Description: Name of the namespace - used as prefix for the AWS resources.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AwsNamespace}-service-two-lambda
      AccessControl: AuthenticatedRead
