version: '3.8'

services:
  lambda_npm_app:
    image: lambci/lambda:build-nodejs10.x
    volumes:
      - .:/var/task
    networks:
      - monsoon-samples_default

  sam_app:
    build: .
    command: ["$PWD"]
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monsoon-samples_default

networks:
  monsoon-samples_default:
    name: monsoon-samples_default
